/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
//aca es la ubicacion de la clase 
package InterfazGUI;
//se importan las librerias y clases que necesita el sistema para funcionar 
import Modelo.Banco;
import Modelo.Cliente;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author benal
 */
public class IngresoUsuario extends javax.swing.JDialog {
// se encarga de verificar si se esta creando un usuario nuevo o solo se esta editando
    private Cliente clienteEditar = null; //no carga datos del cliente 
    private boolean esEdicion = false;//  carga datos del cliente 
    private int indiceEdicion = -1;
    /**
     * Creates new form IngresoUsuario
     * @param parent
     * @param modal
     */
    public IngresoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana

        // Quitar selección de los grupos de radio buttons
        GeneroCliente.clearSelection();
        TipoTramite.clearSelection();

        // Colocar los ComboBox en la primera opción ("Seleccione...")
        cbxDiscapacidad.setSelectedIndex(0);
        cbxBebe.setSelectedIndex(0);
        
    }
    
    public IngresoUsuario(java.awt.Frame parent, boolean modal, Cliente cliente, int indice) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana

        //Cargar valores para modo edición
        this.clienteEditar = cliente;
        this.esEdicion = true;
        this.indiceEdicion = indice;

        //Precargar datos en campos de entrada
        txtNombre.setText(cliente.getNombre());
        txtEdad.setText(String.valueOf(cliente.getEdad()));

        jrbHombre.setSelected(cliente.getGenero() == 'M');
        jrbMujer.setSelected(cliente.getGenero() == 'F');

        cbxDiscapacidad.setSelectedItem(cliente.tieneDiscapacidad() ? "Sí" : "No");
        cbxBebe.setSelectedItem(cliente.tieneBebe() ? "Sí" : "No");

        //Seleccionar tipo de trámite
        if (cliente.getTramite() == 'D') {
            jrbMultiplesTramites.setSelected(true);
        } else if (cliente.getTramite() == 'E') {
            jrbPlataforma.setSelected(true);
        } else {
            jrbOtroCaso.setSelected(true);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneroCliente = new javax.swing.ButtonGroup();
        TipoTramite = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTituloNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        generoCliente = new javax.swing.JLabel();
        lblTituloEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblTituloBebe = new javax.swing.JLabel();
        lblTituloDiscapacidad = new javax.swing.JLabel();
        cbxDiscapacidad = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cbxBebe = new javax.swing.JComboBox<>();
        jrbMujer = new javax.swing.JRadioButton();
        jrbHombre = new javax.swing.JRadioButton();
        lblTituloTramite = new javax.swing.JLabel();
        jrbMultiplesTramites = new javax.swing.JRadioButton();
        jrbPlataforma = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrbOtroCaso = new javax.swing.JRadioButton();
        btnVerClientes = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(184, 249, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloNombre.setText("Nombre y Apellidos");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 126, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 164, -1));

        generoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoCliente.setText("Seleccione su genero");
        jPanel1.add(generoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lblTituloEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloEdad.setText("Edad:");
        jPanel1.add(lblTituloEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 203, 50, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 71, -1));

        lblTituloBebe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloBebe.setText("Tiene algún bebé en brazos");
        jPanel1.add(lblTituloBebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 331, 155, -1));

        lblTituloDiscapacidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloDiscapacidad.setText("Tiene alguna discapacidad");
        jPanel1.add(lblTituloDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 152, -1));

        cbxDiscapacidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "No", "Sí" }));
        jPanel1.add(cbxDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        cbxBebe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxBebe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "No", "Sí" }));
        jPanel1.add(cbxBebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        GeneroCliente.add(jrbMujer);
        jrbMujer.setText("Mujer");
        jPanel1.add(jrbMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 98, -1));

        GeneroCliente.add(jrbHombre);
        jrbHombre.setText("Hombre");
        jPanel1.add(jrbHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 98, -1));

        lblTituloTramite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloTramite.setText("Cual es su tramite");
        jPanel1.add(lblTituloTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 109, -1));

        TipoTramite.add(jrbMultiplesTramites);
        jrbMultiplesTramites.setText("Multiples Tramites");
        jPanel1.add(jrbMultiplesTramites, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 141, -1));

        TipoTramite.add(jrbPlataforma);
        jrbPlataforma.setText("Plataforma");
        jPanel1.add(jrbPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 98, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Por favor rellene los espacios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 174, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ingreso de Datos Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 253, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 134, 37, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genero.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 71, 49, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edad.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 55, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 64));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generof.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 59, 57));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discapacidad.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 53, 61));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/embarazo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 59, 61));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plataforma.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        TipoTramite.add(jrbOtroCaso);
        jrbOtroCaso.setText("Otro caso");
        jPanel1.add(jrbOtroCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 98, -1));

        btnVerClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerClientes.setText("Ver Clientes");
        btnVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jLabel12.setText("Debe ser mayor de 13");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 // Obtener y limpiar los valores ingresados por el usuario
    String nombre = txtNombre.getText().trim();
    String edadTexto = txtEdad.getText().trim();

    // Verificar si se ha seleccionado género, discapacidad, bebé y tipo de trámite
    boolean generoSeleccionado = jrbHombre.isSelected() || jrbMujer.isSelected();
    boolean discapacidadSeleccionada = cbxDiscapacidad.getSelectedIndex() != 0;
    boolean bebeSeleccionado = cbxBebe.getSelectedIndex() != 0;
    boolean tramiteSeleccionado = jrbMultiplesTramites.isSelected() || 
                                   jrbPlataforma.isSelected() || 
                                   jrbOtroCaso.isSelected();

    // Validar que todos los campos estén completos
    if (nombre.isEmpty() || 
        edadTexto.isEmpty() || 
        !generoSeleccionado || 
        !discapacidadSeleccionada || 
        !bebeSeleccionado || 
        !tramiteSeleccionado) {
        
        JOptionPane.showMessageDialog(this, 
            "Por favor complete todos los campos.", 
            "Estimado Cliente", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que la edad sea un número entero válido entre 13 y 120
    int edad;
    try {
        edad = Integer.parseInt(edadTexto);
        if (edad < 13 || edad > 120) {
            JOptionPane.showMessageDialog(this, 
                "La edad no es válida.", 
                "Estimado Cliente", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Su edad debe ser un número entero.", 
            "Estimado Cliente", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtener el género seleccionado ('M' para hombre, 'F' para mujer)
    char genero = jrbHombre.isSelected() ? 'M' : 'F';

    // Convertir las opciones de discapacidad y bebé a valores booleanos
    boolean discapacidad = cbxDiscapacidad.getSelectedItem().equals("Sí");
    boolean bebe = cbxBebe.getSelectedItem().equals("Sí");

    // Verificar si se marcó "Otro caso"
    boolean otroCaso = jrbOtroCaso.isSelected();

    // Determinar el tipo de trámite:
    // 'D' para múltiples trámites, 'E' para plataforma, 
    // 'F' si es mujer y no aplica los anteriores, 'G' si es hombre
    char tramite;
    if (jrbMultiplesTramites.isSelected()) {
        tramite = 'D';
    } else if (jrbPlataforma.isSelected()) {
        tramite = 'E';
    } else {
        tramite = (genero == 'F') ? 'F' : 'G';
    }

    // Definir la tolerancia según el género (8 para mujer, 6 para hombre)
    int tolerancia = (genero == 'F') ? 8 : 6;

    // Crear un nuevo objeto Cliente con los datos recolectados
    Cliente nuevo = new Cliente(nombre, genero, discapacidad, bebe, tramite, tolerancia, edad, otroCaso);

    // Si se está editando un cliente existente
    if (esEdicion) {
        Banco.getInstancia().reemplazarCliente(indiceEdicion, nuevo);
        JOptionPane.showMessageDialog(this, 
            "Cliente editado con éxito. Nuevo código: " + nuevo.getCodigo());
        this.dispose(); // cerrar ventana actual
    } else {
        // Si es un cliente nuevo, agregarlo al banco
        Banco.getInstancia().agregarCliente(nuevo);
        JOptionPane.showMessageDialog(this, 
            "Cliente agregado con éxito. Código: " + nuevo.getCodigo());

        // Limpiar los campos del formulario para un nuevo registro
        txtNombre.setText("");
        txtEdad.setText("");
        GeneroCliente.clearSelection();
        TipoTramite.clearSelection();
        cbxDiscapacidad.setSelectedIndex(0);
        cbxBebe.setSelectedIndex(0);

        // Mostrar ventana de resumen y cerrar esta ventana
        ResumenCliente resumen = new ResumenCliente();
        this.dispose(); // cerrar formulario actual
        resumen.setVisible(true);

        // Si esta ventana fue abierta desde CrudCliente, cerrarla también
        Window parent = SwingUtilities.getWindowAncestor(this);
        if (parent != null && parent instanceof CrudCliente) {
            parent.setVisible(false);
        }
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();// cierra la ventana
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        CrudCliente crudCliente = new CrudCliente(); // llama a la tabla 
        crudCliente.setVisible(true); // Mostrar la ventana
        dispose(); // Cerrar la ventana actual (IngresoUsuario)
    }//GEN-LAST:event_btnVerClientesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GeneroCliente;
    private javax.swing.ButtonGroup TipoTramite;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JComboBox<String> cbxBebe;
    private javax.swing.JComboBox<String> cbxDiscapacidad;
    private javax.swing.JLabel generoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbHombre;
    private javax.swing.JRadioButton jrbMujer;
    private javax.swing.JRadioButton jrbMultiplesTramites;
    private javax.swing.JRadioButton jrbOtroCaso;
    private javax.swing.JRadioButton jrbPlataforma;
    private javax.swing.JLabel lblTituloBebe;
    private javax.swing.JLabel lblTituloDiscapacidad;
    private javax.swing.JLabel lblTituloEdad;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloTramite;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
